OPENROUTER_KEY="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"
SUPABASE_URL="https://vgyfjrnpecfebplytafg.supabase.co"
SUPABASE_KEY="sb_publishable_QYYGfPW5cYgI_UsKNrpkMw_BZUG7yZi"